Proyecto2ProgramacionAvanzadaWeb/Controllers/BonusesController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto2ProgramacionAvanzadaWeb.IServices;
using Proyecto2ProgramacionAvanzadaWeb.Models;
using Proyecto2ProgramacionAvanzadaWeb.Utils;
using Proyecto2ProgramacionAvanzadaWeb.ViewModel;

namespace Proyecto2ProgramacionAvanzadaWeb.Controllers
{
    public class BonusesController : Controller
    {
        private readonly IEmployeesService _employeesService;
        private readonly IBonusesService _bonusesServices;
        private readonly IEmployeeBonusesService _employeeBonusesService;

        public BonusesController(IEmployeesService employeesService, IBonusesService bonusesService, IEmployeeBonusesService employeeBonusesService)
        {
            _employeesService = employeesService;
            _bonusesServices = bonusesService;
            _employeeBonusesService = employeeBonusesService;
        }

        [HttpGet]
        public async Task<IActionResult> Assign()
        {
            try
            {
                List<Bonuses> employeeBonuses = new List<Bonuses>();
                List<Bonuses> Bonuses = new List<Bonuses>();
                Employees employee = await _employeesService.GetById(HttpContext.Session.GetObjectFromJson<int>("EmployeeNumber"));
                if (employee != null)
                {
                    foreach (EmployeeBonuses item in employee?.EmployeeBonuses)
                    {
                        employeeBonuses.Add(item.Bonuses);
                    }
                }

                Bonuses = await _bonusesServices.GetAll();
                if (Bonuses == null)
                {
                    Bonuses = new List<Bonuses>();
                }
                else
                {
                    Bonuses.RemoveAll(b => employeeBonuses.Any(eb => eb.BonusId == b.BonusId));

                }

                BonusesView bonusesView = new BonusesView(employeeBonuses, Bonuses);

                return View(bonusesView);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Add(int id)
        {
            try
            {
                Employees employee = await _employeesService.GetById(HttpContext.Session.GetObjectFromJson<int>("EmployeeNumber"));
                if(await _employeeBonusesService.Add(employee.EmployeeNumber, id))
                {
                    TempData["Success"] = "Bono asignado correctamente";
                }
                else
                {
                    TempData["Error"] = "Error: No se puedo asignar el bono, intente nuevamente";
                }
                
                return RedirectToAction("Assign");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            try
            {
                Employees employee = await _employeesService.GetById(HttpContext.Session.GetObjectFromJson<int>("EmployeeNumber"));
                if (await _employeeBonusesService.Remove(employee.EmployeeNumber, id))
                {
                    TempData["Success"] = "Bono eliminado correctamente";
                }
                else
                {
                    TempData["Error"] = "Error: No se puedo eliminar el bono, intente nuevamente";
                }

                return RedirectToAction("Assign");
            }
            catch (Exception ex)
            {
                return View();
            }
        }
    }
}

Proyecto2ProgramacionAvanzadaWeb/Views/Bonuses/Assign.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Proyecto2ProgramacionAvanzadaWeb.ViewModel.BonusesView
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

@if (@TempData["Success"] != null)
{
    <script src="/lib/jquery///dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}

@if (@TempData["Error"] != null)
{
    <script src="/lib/jquery///dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData["Error"]');
    </script>
}

<div class="row">
    <div class="col-md-6 mb-4">
        <h2>Asignados</h2>
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr>
                    <th>Nombre</th>
                    <th>Monto Mensual</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var bonus in Model.BonusesAssigned)
                {
                    <tr>
                        <td>@bonus.BonusName</td>
                        <td>@bonus.MontlyAmount</td>
                        <td>
                            <div class="btn-group">
                                <a asp-controller="Bonuses" asp-action="Remove" asp-route-id="@bonus.BonusId" class="btn btn-danger" title="Quitar">
                                    <i class="fas fa-remove"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-6 mb-4">
        <h2>Sin asignar</h2>
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr>
                    <th>Nombre</th>
                    <th>Monto Mensual</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var bonus in Model.BonusesAvailable)
                {
                    <tr>
                        <td>@bonus.BonusName</td>
                        <td>@bonus.MontlyAmount</td>
                        <td>
                            <a asp-controller="Bonuses" asp-action="Add" asp-route-id="@bonus.BonusId" class="btn btn-success" title="Asignar">
                                <i class="fas fa-plus"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>